#ifndef PNIOCTLS_H
#define PNIOCTLS_H

//
// List of IOCTLs in p9rdr!p9fs::P9DevFcbXXXControlFile
//

// Don't be confused with FSCTL codes in ntifs.h file
// 0x140007u
#define FSCTL_P9RX_CONNECTION_REQUEST_CLOSE \
    CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM, 1, METHOD_NEITHER, FILE_ANY_ACCESS)

// 0x14000Bu
#define FSCTL_P9RX_CONNECTION_FORCE_CLOSE \
    CTL_CODE(FILE_DEVICE_NETWORK_FILE_SYSTEM, 2, METHOD_NEITHER, FILE_ANY_ACCESS)

// 0x220007u
#define IOCTL_PNRDR_START_MINI_REDIRECTOR \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 1, METHOD_NEITHER, FILE_ANY_ACCESS)

// 0x220008u
#define IOCTL_PNRDR_ADD_CONNECTION_TARGET \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 2, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 0x22000Cu
#define IOCTL_PNRDR_REMOVE_CONNECTION_TARGET \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 3, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 0x220013u
#define IOCTL_PNRDR_ENSURE_REDIRECTOR_STARTED \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 4, METHOD_NEITHER, FILE_ANY_ACCESS)

// 0x220014u
#define IOCTL_PNRDR_REGISTER_USER_CALLBACK \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 5, METHOD_BUFFERED, FILE_ANY_ACCESS)

// 0x220018u
#define IOCTL_PNRDR_ENUMERATE_CONNECTIONS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 6, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif // PNIOCTLS_H
